APIKEY = "pq6XmGX15x3YVZgcMds5l3GNggTaQGXATW0ethemqHwEO2ULWFmLSd5NskaNnYr6"
SECRETKEY = "MMYKgPUyVTlYm74LPVCpUawPlQHkU51d2bDKxHJfVj6kBU0Rp7OoBMmVA0d7yrEA"

DB_URL = "https://binanceproject-75cf3-default-rtdb.firebaseio.com/"

TICKER_DB_NAME = "master"
TICKER_DB_USER = "master"
TICKER_DB_PASS = "123"
TICKER_DB_HOST = "88.218.248.140"

TG_URL = 'https://api.telegram.org/bot'
TG_API_ONE = "6510784847:AAHFay6eKHZblq18WcRZwY6ipHzODnomBg8"
TG_API_TWO = "6382495537:AAGe-XXy36pEB-8enF6q9qwxAwk0xqgGfKU"

host = "127.0.0.1"
user = "root"
password = "pass123"


symbols = ['SUSHIUSDT', 'INJUSDT']
futures_symbols = [
    "WOOUSDT", "XTZUSDT", "XRPUSDT", "XMRUSDT", "XLMUSDT", "XEMUSDT", "WLDUSDT",
    # 'ZRXUSDT', 'ZILUSDT', 'ZENUSDT', 'ZECUSDT', 'YGGUSDT', 'YFIUSDT', 'XVGUSDT', 'XTZUSDT',
    # 'ZRXUSDT.P', 'ZILUSDT.P', 'ZENUSDT.P', 'ZECUSDT.P', 'YGGUSDT.P', 'YFIUSDT.P', 'XVGUSDT.P', 'XTZUSDT.P',
    # 'XRPUSDT.P', 'XMRUSDT.P', 'XLMUSDT.P', 'XEMUSDT.P', 'WOOUSDT.P', 'WLDUSDT.P', 'WAVESUSDT.P', 'VETUSDT.P',
    # 'UNIUSDT.P', 'UNFIUSDT.P', 'UMAUSDT.P', 'TUSDT.P', 'TRXUSDT.P', 'TRUUSDT.P', 'TRBUSDT.P', 'TOMOUSDT.P',
    # 'TLMUSDT.P', 'THETAUSDT.P', 'SXPUSDT.P', 'SUSHIUSDT.P', 'SUIUSDT.P', 'STXUSDT.P', 'STORJUSDT.P',
    # 'STMXUSDT.P', 'STGUSDT.P', 'SSVUSDT.P', 'SPELLUSDT.P', 'SOLUSDT.P', 'SNXUSDT.P', 'SFPUSDT.P', 'SANDUSDT.P',
    # 'RVNUSDT.P', 'RUNEUSDT.P', 'RSRUSDT.P', 'ROSEUSDT.P', 'RNDRUSDT.P', 'RLCUSDT.P', 'RENUSDT.P', 'REEFUSDT.P',
    # 'RADUSDT.P', 'QTUMUSDT.P', 'QNTUSDT.P', 'PHBUSDT.P', 'PERPUSDT.P', 'PEOPLEUSDT.P', 'OPUSDT.P', 'ONTUSDT.P',
    # 'ONEUSDT.P', 'OMGUSDT.P', 'OGNUSDT.P', 'OCEANUSDT.P', 'NKNUSDT.P', 'NEOUSDT.P', 'NEARUSDT.P', 'MTLUSDT.P',
    # 'MKRUSDT.P', 'MINAUSDT.P', 'MDTUSDT.P', 'MAVUSDT.P', 'MATICUSDT.P', 'MASKUSDT.P', 'MANAUSDT.P', 'MAGICUSDT.P',
    # 'LUNA2USDT.P', 'LTCUSDT.P', 'LRCUSDT.P', 'LQTYUSDT.P', 'LPTUSDT.P', 'LITUSDT.P', 'LINKUSDT.P', 'LINAUSDT.P',
    # 'LEVERUSDT.P', 'LDOUSDT.P', 'KSMUSDT.P', 'KNCUSDT.P', 'KLAYUSDT.P', 'KEYUSDT.P', 'KAVAUSDT.P', 'JOEUSDT.P',
    # 'JASMYUSDT.P', 'IOTXUSDT.P', 'IOTAUSDT.P', 'IOSTUSDT.P', 'INJUSDT.P', 'IMXUSDT.P', 'IDUSDT.P', 'IDEXUSDT.P',
    # 'ICXUSDT.P', 'ICPUSDT.P', 'HOTUSDT.P', 'HOOKUSDT.P', 'HIGHUSDT.P', 'HBARUSDT.P', 'GTCUSDT.P', 'GRTUSDT.P',
    # 'GMXUSDT.P', 'GMTUSDT.P', 'GALUSDT.P', 'GALAUSDT.P', 'FXSUSDT.P', 'FTMUSDT.P', 'FOOTBALLUSDT.P', 'FLOWUSDT.P',
    # 'FLMUSDT.P', 'FILUSDT.P', 'FETUSDT.P', 'ETHUSD.P', 'ETCUSDT.P', 'EOSUSDT.P', 'ENSUSDT.P', 'ENJUSDT.P',
    # 'EGLDUSDT.P', 'EDUUSDT.P', 'DYDXUSDT.P', 'DUSKUSDT.P', 'DOTUSDT.P', 'DOGEUSDT.P', 'DGBUSDT.P', 'DENTUSDT.P',
    # 'DEFIUSDT.P', 'DASHUSDT.P', 'DARUSDT.P', 'CVXUSDT.P', 'CTSIUSDT.P', 'CTKUSDT.P', 'CRVUSDT.P', 'COTIUSDT.P',
    # 'COMPUSDT.P', 'COMBOUSDT.P', 'CKBUSDT.P', 'CHZUSDT.P', 'CHRUSDT.P', 'CFXUSDT.P', 'CELRUSDT.P', 'CELOUSDT.P',
    # 'C98USDT.P', 'BTCUSDT.P', 'BNXUSDT.P', 'BNBUSDT.P', 'BLZUSDT.P', 'BLUEBIRDUSDT.P', 'BLURUSDT.P', 'BCHUSDT.P',
    # 'BATUSDT.P', 'BANDUSDT.P', 'BALUSDT.P', 'BAKEUSDT.P', 'AXSUSDT.P', 'AVAXUSDT.P', 'AUDIOUSDT.P', 'ATOMUSDT.P',
    # 'ATAUSDT.P', 'ASTRUSDT.P', 'ARPAUSDT.P', 'ARBUSDT.P', 'APTUSDT.P', 'API3USDT.P', 'APEUSDT.P', 'ANTUSDT.P',
    # 'ANKRUSDT.P', 'AMBUSDT.P', 'ALPHAUSDT.P', 'ALICEUSDT.P', 'ALGOUSDT.P', 'AGIXUSDT.P', 'ADAUSDT.P', 'ACHUSDT.P',
    # 'AAVEUSDT.P', '1INCHUSDT.P', '1000XECUSDT.P', '1000SHIBUSDT.P', '1000PEPEUSDT.P', '1000LUNCUSDT.P',
    # '1000FLOKIUSDT.P',
]
# symbols = ['SUSHIUSDT', 'BTSUSDT', 'INJUSDT', 'RDNTUSDT', 'ZRXUSDT', 'HIGHUSDT', 'WAVESUSDT', 'SPELLUSDT',
#            'BNBUSDT', 'XTZUSDT', 'DARUSDT', 'HNTUSDT', 'JOEUSDT', 'XMRUSDT', 'ETCUSDT', 'PENDLEUSDT',
#            'ALICEUSDT', 'HOOKUSDT', 'REEFUSDT', 'BATUSDT', 'DOGEUSDT', 'TRXUSDT', 'STORJUSDT', 'SNXUSDT',
#            'XLMUSDT', 'IOTXUSDT', 'DASHUSDT', 'UMAUSDT', 'KAVAUSDT', 'RUNEUSDT', 'APEUSDT', 'BLUEBIRDUSDT',
#            'BNXUSDT', 'OPUSDT', 'KEYUSDT', 'DGBUSDT', 'SKLUSDT', 'FOOTBALLUSDT', 'TOMOUSDT', 'MTLUSDT',
#            'LTCUSDT', 'KSMUSDT', 'TRBUSDT', 'MANAUSDT', 'FLOWUSDT', 'CHRUSDT', 'GALUSDT', 'OGNUSDT', 'RNDRUSDT',
#            'SCUSDT', 'STMXUSDT', 'KNCUSDT', 'SRMUSDT', 'BLURUSDT', 'ENJUSDT', 'ATOMUSDT', 'NMRUSDT', 'ENSUSDT',
#            'ATAUSDT', 'AGIXUSDT', 'IOSTUSDT', 'HBARUSDT', 'ZECUSDT', 'IDEXUSDT', 'GALAUSDT', 'EDUUSDT',
#            'GTCUSDT', 'ALGOUSDT', 'LRCUSDT', 'STGUSDT', 'STXUSDT', 'ARPAUSDT', 'CELOUSDT', 'QNTUSDT',
#            'INCHUSDT', 'TUSDT', 'LINAUSDT', 'ARUSDT', 'FILUSDT', 'SOLUSDT', 'BLZUSDT', 'COMBOUSDT', 'GMTUSDT',
#            'MDTUSDT', 'XVSUSDT', 'GMXUSDT', 'BANDUSDT', 'LDOUSDT', 'XRPUSDT', 'FTTUSDT', 'CRVUSDT', 'BELUSDT',
#            'DOTUSDT', 'ONEUSDT', 'APTUSDT', 'ANKRUSDT', 'MAVUSDT', 'RAYUSDT', 'API3USDT', 'CVCUSDT', 'ASTRUSDT',
#            'HOTUSDT', 'QTUMUSDT', 'IOTAUSDT', 'ADAUSDT', 'LITUSDT', 'YFIUSDT', 'ALPHAUSDT', 'WOOUSDT',
#            'SFPUSDT', 'RLCUSDT', 'BTCSTUSDT', 'XECUSDT', 'FXSUSDT', 'CFXUSDT', 'AUDIOUSDT', 'IDUSDT', 'HFTUSDT',
#            'NEOUSDT', 'UNFIUSDT', 'SANDUSDT', 'CTKUSDT', 'LINKUSDT', 'MINAUSDT', 'CELRUSDT', 'AGLDUSDT',
#            'RSRUSDT', 'RENUSDT', 'LPTUSDT', 'JASMYUSDT', 'PHBUSDT', 'YGGUSDT', 'EGLDUSDT', 'LUNA2USDT',
#            'ONTUSDT', 'VETUSDT', 'IMXUSDT', 'LQTYUSDT', 'COTIUSDT', 'CVXUSDT', 'ARBUSDT', 'BAKEUSDT', 'GRTUSDT',
#            'FLMUSDT', 'MASKUSDT', 'EOSUSDT', 'BALUSDT', 'COCOSUSDT', 'SUIUSDT', 'DENTUSDT', 'TRUUSDT',
#            'CKBUSDT', 'SSVUSDT', 'C98USDT', 'ZENUSDT', 'NEARUSDT', 'BCHUSDT', 'SHIBUSDT', 'ANTUSDT', 'TLMUSDT',
#            'AAVEUSDT', 'ICPUSDT', 'LUNCUSDT', 'RADUSDT', 'AVAXUSDT', 'MAGICUSDT', 'ROSEUSDT', 'MATICUSDT',
#            'XVGUSDT', 'MKRUSDT', 'PEOPLEUSDT', 'THETAUSDT', 'UNIUSDT', 'PERPUSDT', 'RVNUSDT', 'ARKMUSDT',
#            'NKNUSDT', 'KLAYUSDT', 'DEFIUSDT', 'COMPUSDT', 'BTCDOMUSDT', 'OMGUSDT', 'ICXUSDT', 'PEPEUSDT',
#            'FETUSDT', 'LEVERUSDT', 'FLOKIUSDT', 'FTMUSDT', 'AMBUSDT', 'SXPUSDT', 'XEMUSDT', 'WLDUSDT',
#            'ZILUSDT', 'DYDXUSDT', 'AXSUSDT', 'OCEANUSDT', 'CHZUSDT', 'DUSKUSDT', 'CTSIUSDT', 'ACHUSDT']
